# Permitir acceso local
local   all             all                                     trust

# Permitir acceso interno en docker
host    all             all             172.16.0.0/12            md5

# Permitir cualquier IP externa (opción abierta)
host    all             all             0.0.0.0/0                md5

# Para mayor seguridad:
# host    all            all         <TU_IP>/32                md5
